### ISSUE TITLE
Add "multi-room-synchronisation" and "DLNA" capability categories to server

### ISSUE THREAD

**Issue by asche77** [basings/selfhosted-music-overview#100]
Multi-room: e.g. Sonos and Logitech Media Server have the capability to keep several players in sync.

DLNA: a very basic server "API" but compatible with most players. (I would expect most servers to tick this box, e.g. confirmed for Plex and Logitech Media Server)

**Comment by basings** [comment]
great idea @asche77 , thx! How would we best add this? By a col `Multi Room` with :heavy_check_mark: and :x: or an entry with `DLNA`? Are there alternatives to DLNA?

**Comment by asche77** [comment]
Hi @basings , that's two separate columns.  I would suggest "multi room" yes/no as per your suggestion.

DLNA is probably supported by virtually all servers, so it's more for completeness. Not sure we really need to add it. (https://en.m.wikipedia.org/wiki/Digital_Living_Network_Alliance)

**Comment by basings** [comment]
I added a multi-room col

**Comment by asche77** [comment]
Please tick multi-room for Logitech Media Server :-)
