### ISSUE TITLE
add col for musicbrainz integration 

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#12]

**Comment by BillButter** [comment]
We might run into issues with the specifics, but I do like this idea. Navidrome, for example, Has MB integration in the form of a link that takes you to it's MB page.

![image](https://user-images.githubusercontent.com/63459838/138332960-9ab4703a-ca22-4a3b-9c4c-782f7cc1ec21.png)

It can't write tags based on MB. 


One option we have is to rename "Can Write Tags" to "Can Write Tags pulled from MB" or something.

**Comment by basings** [comment]
column: Musicbrainz
cell: either :x: or :heavy_check_mark: or :heavy_check_mark: [^readonly]

[^readonly]: cannot write to database

?
