### ISSUE TITLE
Enhance `scrobble` column 

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#129]
Just specifying if it supports scrobbling :heavy_check_mark: or if it doesn't :x: might not be enough. There are several scrobble services and if a service supports last.fm it doesn't mean that it supports another service

**Comment by BillButter** [comment]
Are there more than last.fm and listenbrainz? If there are only the two, we could have a column for each

**Comment by basings** [comment]
yes, there are more than those, e.g. libre.fm, but last.fm is probably the most popular one.
