### ISSUE TITLE
Fix Lightweight Music Server

### ISSUE THREAD

**Issue by epoupon** [basings/selfhosted-music-overview#151]
Hello,

Thanks for your work. Some corrections about Lightweight Music Server:
* NO jukebox mode
* CANNOT write tags
* HAS Subsonic API
* CANNOT share music
* NO multi library support
* NO 5 stars rating
* HAS Replay gain support
* CAN transcode
* NO DNLA
* NO multi room
* NO lyrics
* Demo website: https://lms-demo.poupon.dev/ (other link will expire soon)
* Reviewed Version: 3.27.0

About the web player:
* OS: Web
* Gapless Playback: no
* Album view: yes
* Songs view: yes
* Folder view: NO
* Albm Artist View : yes
* Artist view : yes
* Genre view : yes
* Decade view: NO
* Year view: NO
* Playlist support: NO
* Most Played song: yes
* Most played album: yes
* Recently played sonc : yes
* Recently played albums : yes
* Recently added song : yes
* Recently added album : yes
* Frequently played album: yes
* offline mode: no
* download music : yes
* podcasts: no
* scrobbling : yes
* musicbrainz: yes
* similar songs: yes
* artist top songs: no
* shufflep lay : yes
* random albums : yes
* favorites/starred: yes
* bookmarks: no
* 5 stars: no
* search function : yes
* chromecast support: no
* android auto : N/A
* dark mode: yes
* themeable: no
* open source: yes
* free: yes
* smart recommendations: yes
* video support : no
* internet radio: no
* Lyrics: no
* API: proprietary
* fdroid: N/A
* source code: same as LMS
* License: GPLv3
* Reviewed version: 3.27.0

**Comment by basings** [comment]
@epoupon Thank you very much for writing down the info, I created two PRs for the info. #153 and #154 . Does the web player have a name? (I named it Lightweight Music Web Player for now)

**Comment by basings** [comment]
@epoupon if the web player uses the proprietary API, shouldn't the server also use the proprietary API (in addition to subsonic?)?

**Comment by epoupon** [comment]
This is a good question. Actually, the web player is rendered directly by the server, it cannot exists "alone" as it is part of the server.
So yeah I put "proprietary" but we could as well put N/A.

**Comment by basings** [comment]
@epoupon thx for the clarification!
