### ISSUE TITLE
Add SubMusic client 

### ISSUE THREAD

**Issue by memen45** [basings/selfhosted-music-overview#173]
I built SubMusic and I think it should be on this list! It supports Subsonic, Ampache and Plex APIs and is available on Garmin watches through the [Connect IQ app store](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794). 

 |                                                              |      OS      |  Gapless Playback  |     Album View     |     Songs View     |    Folder View     |    Artist View     |     Genre View     |    Decade View     |     Year View      |  Playlist Support  |  Most Played Song  | Most Played Album  | Recently Played Song | Recently Played Album | Recently Added Song | Recently Added Album | Frequently Played Album |     Offline Mode     |              Download Music               |      Podcasts      |     Scrobbling     |              Musicbrainz               |   Similar Songs    |  Artist Top Songs  |    Shuffle Play    |    Random Album    | Favorites / Starred / Bookmark |      5 Stars       |  Search function   | Chromecast Support |  Android Auto   |     Dark Mode      |     Themeable      |    Open Source     |        free        | Smart Recommendations |   Video Support    |   Internet Radio   |                 API                 |                           f-droid                            |                         Source Code                          |                        License                        | Reviewed Version |                                                             |
| ------------------------------------------------------------ | :----------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :------------------: | :-------------------: | :-----------------: | :------------------: | :---------------------: | :------------------: | :---------------------------------------: | :----------------: | :----------------: | :------------------------------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------------------: | :----------------: | :----------------: | :----------------: | :-------------: | :----------------: | :----------------: | :----------------: | :----------------: | :-------------------: | :----------------: | :----------------: | :---------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: | :---------------------------------------------------: | :--------------: | ----------------------------------------------------------- |
|                                                              |              |                    |                    |                    |                    |                    |                    |                    |                    |                     |                    |                    |                      |                       |                  |                      |                         |                      |                                           |                    |                    |                                        |                    |                    |                    |                    |                                |                    |                    |                    |                 |                    |                    |                    |                  |                       |                    |                    |                                     |                                                              |                                                              |                                                       |                  |                                                             |
| [SubMusic](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794)         |     Garmin      |                    |                    |                    |                    |                    |                    |                    |                    |               :heavy_check_mark:     |                    |                    |                      |                       |                     |                      |                        |                :heavy_check_mark:      |                :heavy_check_mark:                           |        :heavy_check_mark:            |           :heavy_check_mark:         |                                     |                    |                    |         :heavy_check_mark:           |                    |                                |                    |                    |                    |                 |                    |                    |     :heavy_check_mark:                |           :heavy_check_mark:         |                       |                    |                    |              Subsonic, Ampache, Plex               |                        :white_circle:                        |      [GitHub](https://github.com/memen45/submusic)       | [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) |         0.2.8-oebalus         | [SubMusic](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794)                                                   |

**Comment by basings** [comment]
looks like a cool app! Kudos! do you want to open a pr or shall I?

**Comment by memen45** [comment]
Thanks! I created a PR for you #175
