### ISSUE TITLE
License

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#4]

**Comment by basings** [comment]
- GPL3 is a great license. It guarantess that nobody can commercialize on this work. 
  - https://www.gnu.org/licenses/gpl-3.0.en.html
  - [![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
- MIT License is great because it's easy to understand and you can do whatever you want with the software.
  - https://mit-license.org/
  - [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

I have no experience with other licenses. I don't much care, what's your take on this @BillButter ?

**Comment by basings** [comment]
I'd like to go for GPLv3

**Comment by joshuaboniface** [comment]
The GFDL or a Creative Commons license might be a good choice since this is mostly documentation (rather than code)!

**Comment by basings** [comment]
@joshuaboniface that's a good idea thx! 

I had a deeper look into the licenses, do you have a recommendation? 

CC BY-SA 3.0 sounds good

https://creativecommons.org/licenses/by-sa/3.0/legalcode

**Comment by basings** [comment]
But  [![License: FDL 1.3](https://img.shields.io/badge/License-FDL_v1.3-blue.svg)](https://www.gnu.org/licenses/fdl-1.3) sounds good too, maybe even better.

**Comment by joshuaboniface** [comment]
Either or is probably fine, both are going to achieve the same thing in practice. IIRC the CC licenses are more "battle-tested" in a legal sense, but as long as there's share-alike requirements you'll end up with the same intent as the GPL ;-)

**Comment by basings** [comment]
alright, thx!
let's go for FDL, easy peasy

**Comment by basings** [comment]
tank you guys, let's close this.
