### ISSUE TITLE
[Feature Update] Add Smart Playlist Feature to Navidrome

### ISSUE THREAD

**Issue by quietmansoath** [basings/selfhosted-music-overview#57]
This is a brand new feature, but they have in fact implemented this, so the chart needs updating.

Separately, this is a very helpful chart, so thank you for the contribution.

**Comment by basings** [comment]
Hey @quietmansoath thx for reporting this! Would you like to make a PR? Otherwise I'll make one later on

Thx, I'm glad it's useful!
