### ISSUE TITLE
review information

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#7]

**Comment by BillButter** [comment]
What do you mean by this

**Comment by basings** [comment]
agreed. nice! 

I suggest that enough information must be provided such that the reviewer can verify the source himself. You don't have to provide a screenshot for "Artist view", "song view" etc. you just need to be able to download the app. This is easy on the client side. On the server side this might be more complex



shall we empty the tables then?

**Comment by basings** [comment]
let's leave the content in the cells for now. 

We can remove the content before we start filling out the table. If we clean it now, it looks sad :D
