### ISSUE TITLE
rename LMS to lightweight music server

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#77]

**Comment by billotronic** [comment]
There are two listings, one for LMS and one for Logitech Media Server. I've gotten as far that they do not match, but I'm pretty sure neither is accurate. ;

**Comment by basings** [comment]
@billotronic what do you mean by "neither is accurate?" Which info is false? Logitech media server was added by @BillButter in pre github times. 
LMS actually refers to [lms](https://github.com/epoupon/lms)

**Comment by basings** [comment]
It was actually added by @asche77 not @BillButter , sorry for that mistake.
@BillButter added Lightweight music server
