### ISSUE TITLE
[server request] Tauon

### ISSUE THREAD

**Issue by basings** [basings/selfhosted-music-overview#82]
[https://tauonmusicbox.rocks/](https://tauonmusicbox.rocks/)

**Comment by basings** [comment]
|                     |   OS    |  Gapless Playback  |     Album View     |     Songs View     |    Folder View     |    Artist View     |     Genre View     |    Decade View     |     Year View      |  Playlist Support  |  Most Played Song  | Most Played Album  | Recently Played Song | Recently Played Album | Recently Added Song | Recently Added Album | Frequently Played Album |    Offline Mode    |              Download Music               |      Podcasts      |     Scrobbling     |              Musicbrainz               |   Similar Songs    |  Artist Top Songs  |    Shuffle Play    |    Random Album    | Favorites / Starred / Bookmark |      5 Stars       |  Search function   | Chromecast Support |  Android Auto   |     Dark Mode      |     Themeable      |    Open Source     |        free        | Smart Recommendations |   Video Support    |   Internet Radio   |          API           |                 f-droid                 |             Source Code             |                        License                        | Reviewed Version |
| ------------------- | :-----: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :------------------: | :-------------------: | :-----------------: | :------------------: | :---------------------: | :----------------: | :---------------------------------------: | :----------------: | :----------------: | :------------------------------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------------------: | :----------------: | :----------------: | :----------------: | :-------------: | :----------------: | :----------------: | :----------------: | :----------------: | :-------------------: | :----------------: | :----------------: | :--------------------: | :-------------------------------------: | :---------------------------------: | :---------------------------------------------------: | :--------------: |
| [Tauon Music Box](https://github.com/Taiko2k/TauonMusicBox) | Linux |                    |                    |                    |                    |                    |                    |                    |                    |                    |                    |                    |                      |                       |                     |                      |                         |                    |                                           |                    |                    |                                        |                    |                    |                    |                    |                                |                    |                    |                    |                 |                    |                    |  |  |                       |                    |                    |                | :white_circle: | [github-tauon](https://github.com/Taiko2k/TauonMusicBox) | [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) | 6.8.2 |

**Comment by Extarys** [comment]
Hope this works :crossed_fingers: 

|                     |   OS    |  Gapless Playback  |     Album View     |     Songs View     |    Folder View     |    Artist View     |     Genre View     |    Decade View     |     Year View      |  Playlist Support  |  Most Played Song  | Most Played Album  | Recently Played Song | Recently Played Album | Recently Added Song | Recently Added Album | Frequently Played Album |    Offline Mode    |              Download Music               |      Podcasts      |     Scrobbling     |              Musicbrainz               |   Similar Songs    |  Artist Top Songs  |    Shuffle Play    |    Random Album    | Favorites / Starred / Bookmark |      5 Stars       |  Search function   | Chromecast Support |  Android Auto   |     Dark Mode      |     Themeable      |    Open Source     |        free        | Smart Recommendations |   Video Support    |   Internet Radio   |          API           |                 f-droid                 |             Source Code             |                        License                        | Reviewed Version |                     |
| [Tauon Music Box](https://github.com/Taiko2k/TauonMusicBox)               | Linux   | :grey_question:    | :heavy_check_mark: | :heavy_check_mark: | :x:                | :x:                | :x:                | :x:                | :x:                | :heavy_check_mark: | :heavy_check_mark: | :x:                |  :x:                 | :x:                   | :x:                 |  :x:                 | :x:                     |  :x:               |  :x:                                      |  :x:               | :heavy_check_mark: | :x:                                    | :x:                |  :x:               | :heavy_check_mark: |  :x:               | :heavy_check_mark:             | :heavy_check_mark: | :heavy_check_mark: | :x:                | :x:             | :x:                | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:                   |                    |                    | Jellyfin, Plex, Koel, Emby, Spotify |             :white_circle:              | [Github](https://github.com/Taiko2k/TauonMusicBox/) | [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)         |      6.8.2       | Tauon               |


```
|                     |   OS    |  Gapless Playback  |     Album View     |     Songs View     |    Folder View     |    Artist View     |     Genre View     |    Decade View     |     Year View      |  Playlist Support  |  Most Played Song  | Most Played Album  | Recently Played Song | Recently Played Album | Recently Added Song | Recently Added Album | Frequently Played Album |    Offline Mode    |              Download Music               |      Podcasts      |     Scrobbling     |              Musicbrainz               |   Similar Songs    |  Artist Top Songs  |    Shuffle Play    |    Random Album    | Favorites / Starred / Bookmark |      5 Stars       |  Search function   | Chromecast Support |  Android Auto   |     Dark Mode      |     Themeable      |    Open Source     |        free        | Smart Recommendations |   Video Support    |   Internet Radio   |          API           |                 f-droid                 |             Source Code             |                        License                        | Reviewed Version |                     |
| [Tauon Music Box](https://github.com/Taiko2k/TauonMusicBox)               | Linux   | :grey_question:    | :heavy_check_mark: | :heavy_check_mark: | :x:                | :x:                | :x:                | :x:                | :x:                | :heavy_check_mark: | :heavy_check_mark: | :x:                |  :x:                 | :x:                   | :x:                 |  :x:                 | :x:                     |  :x:               |  :x:                                      |  :x:               | :heavy_check_mark: | :x:                                    | :x:                |  :x:               | :heavy_check_mark: |  :x:               | :heavy_check_mark:             | :heavy_check_mark: | :heavy_check_mark: | :x:                | :x:             | :x:                | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:                   |                    |                    | Jellyfin, Plex, Koel, Emby, Spotify |             :white_circle:              | [Github](https://github.com/Taiko2k/TauonMusicBox/) | [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)         |      6.8.2       | Tauon               |
```

**Comment by Extarys** [comment]
Note that Tauon can display synched LRC files from local storage too (I have my music library both from Jellyfin and directly from the file system, so I can sing and make my neighbours cringe when I feel like it.)

**Comment by basings** [comment]
tauon supports gapless playback =)
